Push
kaidou2/homework4 pull request #1
Opened 2022-09-05 07:00 UTC by kaidou2

listにrinseを加えました。

2022-09-05 23:09 UTC, YudaiNoda3576 requested changes
コメントしました！
あと、PRのタイトルは今回の対応内容が分かるものに変えた方が良いと思うのでそちらも対応のほどよろしくお願いします！

2022-09-05 23:09 UTC, YudaiNoda3576 commented on HomeWork4.java
>          names.stream().map(name -> name.getBytes()).forEach(name -> System.out.println(name));
この変更の目的は何でしょうか・・・？🤔

2022-09-05 23:09 UTC, YudaiNoda3576 commented on Webアプリケーション、アプリケーションサーバー、Javaのエディション、Spring Bootについて.txt
> +Webアプリケーション
.txtになっているので.mdに変更してください〜:pray:

2022-09-06 00:32 UTC, kaidou2 commented on HomeWork4.java
>          names.stream().map(name -> name.getBytes()).forEach(name -> System.out.println(name));
rinseを追加した目的は、前回と違う内容のコードにしないといけないと思って、ちょっと追加しただけです。特に意味のあるものではありません。

2022-09-06 01:51 UTC, YudaiNoda3576 reviewed
コメントしました〜

2022-09-06 01:51 UTC, YudaiNoda3576 commented on Webアプリケーション、アプリケーションサーバー、Javaのエディション、Spring Bootについて.md
> +アプリケーションサーバーとはWebサーバーより受け取った情報を処理するためのもの。代表的な種類としてTomcat(Java)、Apache(PHP)、Unicorn(Ruby)などがある。
> Webサーバーより受け取った情報を処理するためのもの

Webサーバについても軽く調べて頂き、Webサーバーとアプリケーションサーバーの違いについても簡単にまとめてみてください！

2022-09-06 01:51 UTC, YudaiNoda3576 commented on Webアプリケーション、アプリケーションサーバー、Javaのエディション、Spring Bootについて.md
> +Java EEとは、企業向けのWebアプリケーション開発ができる機能がセットになったプラットフォームで、正式名称は「Java Platform, Enterprise Edition」という。アプリケーションサーバーの標準規格やそのAPIを定めたもので、サーバーサイド機能が含まれている。
ちょっと課題の趣旨からずれてしまって恐縮なんですが、APIって何か説明できますか？？

2022-09-06 01:51 UTC, YudaiNoda3576 commented on Webアプリケーション、アプリケーションサーバー、Javaのエディション、Spring Bootについて.md
> +Java SE（Java Platform, Standard Edition）とは、Javaの標準的なアプリケーション開発に必要な機能だけをセットにしたもの。Java EEの中にJava SEが含まれているので、Java EEでWebアプリケーション開発するときに、Java SEのライブラリを使用することもできる。
> Javaの標準的なアプリケーション開発に必要な機能

具体的にはどんな機能があるのかもう少し深ぼってみてください！

2022-09-06 03:27 UTC, kaidou2 commented on Webアプリケーション、アプリケーションサーバー、Javaのエディション、Spring Bootについて.md
> +アプリケーションサーバーとはWebサーバーより受け取った情報を処理するためのもの。代表的な種類としてTomcat(Java)、Apache(PHP)、Unicorn(Ruby)などがある。
"Webサーバーとは？"と"アプリケーションサーバーとWebサーバーの違いについて"の所に追加しました。

2022-09-06 03:28 UTC, kaidou2 commented on Webアプリケーション、アプリケーションサーバー、Javaのエディション、Spring Bootについて.md
> +Java EEとは、企業向けのWebアプリケーション開発ができる機能がセットになったプラットフォームで、正式名称は「Java Platform, Enterprise Edition」という。アプリケーションサーバーの標準規格やそのAPIを定めたもので、サーバーサイド機能が含まれている。
"APIとは?"の所に追加しました。

2022-09-06 03:28 UTC, kaidou2 commented on Webアプリケーション、アプリケーションサーバー、Javaのエディション、Spring Bootについて.md
> +Java SE（Java Platform, Standard Edition）とは、Javaの標準的なアプリケーション開発に必要な機能だけをセットにしたもの。Java EEの中にJava SEが含まれているので、Java EEでWebアプリケーション開発するときに、Java SEのライブラリを使用することもできる。
"Java SE EEについて"の所に追加しました。

2022-09-08 05:55 UTC, merged